# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - require_trailing_commas
