# https://github.com/google/mono_repo.dart

stages:
- analyze_format:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk: dev
  - group:
    - analyze: .
    sdk: pubspec
- unit_test:
  - group:
    - test: --run-skipped -t presubmit-only
    sdk: dev
