# https://github.com/google/mono_repo.dart

stages:
- analyze_format:
  - group:
    - format
    - analyze: --fatal-infos .
    dart: dev
  - group:
    - analyze: .
    dart: 2.12.0
- unit_test:
  - group:
    - test: --run-skipped -t presubmit-only
    dart: dev
