line_length:              # MD013 max line length
  stern: true             # allows for lines with no spaces (long URLs), otherwise error
  line_length: 80
  tables: false
html:                     # MD033 no html
  allowed_elements: [br]
headings: true            # MD041 require heading at top of file
images: false             # MD045: image alt text

