name: ffd_workspace

packages:
  - dartfn
  - dartfn/templates/cloudevent
  - dartfn/templates/helloworld
  - dartfn/templates/json
  - examples/fullstack/backend
  - examples/fullstack/frontend-cli
  - examples/hello
  - examples/json
  - examples/protobuf_firestore
  - examples/raw_cloudevent
  - functions_framework
  - functions_framework_builder
  - google_cloud
  - integration_test

command:
  bootstrap:
    usePubspecOverrides: false

scripts:
  build:all:
    description: Build all packages that depend on build_runner.
    run: |
      melos exec --scope="functions_framework" -- dart run build_runner build --delete-conflicting-outputs
      melos exec --scope="__*__" -- dart run build_runner build --delete-conflicting-outputs
      melos exec --scope="dartfn" -- dart run build_runner build --delete-conflicting-outputs
      melos exec --ignore="functions_framework,dartfn,__*__" --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
