name: ffd_workspace

packages:
  - dartfn
  - dartfn/templates/cloudevent
  - dartfn/templates/helloworld
  - dartfn/templates/json
  - examples/fullstack/backend
  - examples/fullstack/frontend-cli
  - examples/hello
  - examples/json
  - examples/protobuf_firestore
  - examples/raw_cloudevent
  - functions_framework
  - functions_framework_builder
  - google_cloud
  - integration_test

command:
  bootstrap:
    usePubspecOverrides: false

scripts:
  build:all:
    description: Build all packages that depend on build_runner.
    run: |
      melos run build:1:functions_framework
      melos run build:2:templates
      melos run build:3:dartfn
      melos run build:4:leafs

  build:1:functions_framework:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      scope: functions_framework

  build:2:templates:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      scope: "__*__"

  build:3:dartfn:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      scope: dartfn

  build:4:leafs:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      ignore:
        - functions_framework
        - dartfn
        - "__*__"
      dependsOn: build_runner
