name: ffd_workspace

packages:
  - dartfn
  - dartfn/templates/cloudevent
  - dartfn/templates/helloworld
  - dartfn/templates/json
  - examples/fullstack/backend
  - examples/fullstack/frontend-cli
  - examples/hello
  - examples/json
  - examples/protobuf_firestore
  - examples/raw_cloudevent
  - functions_framework
  - functions_framework_builder
  - google_cloud
  - integration_test

command:
  bootstrap:
    usePubspecOverrides: false
