builders:
  function_framework_builder:
    import: package:functions_framework_builder/builder.dart
    builder_factories:
      - functionsFrameworkBuilder
    build_extensions:
      'lib/library.dart':
        - bin/server.dart
    auto_apply: dependents
    build_to: source
