builders:
  function_framework_builder:
    import: package:functions_framework_builder/functions_framework_builder.dart
    builder_factories:
      - functionsFrameworkBuilder
    build_extensions:
      $package$:
        - bin/main.dart
    auto_apply: dependents
    build_to: source
