# https://github.com/google/mono_repo.dart
dart:
- 2.14.0
- dev

stages:
- analyze_format:
  - group:
    - format
    - analyze: --fatal-infos .
    dart: dev
  - group:
    - analyze: .
    dart: 2.14.0
- unit_test:
  - test
