# https://github.com/google/mono_repo.dart
stages:
- analyze_format:
  - group:
    - format
    - analyze: --fatal-infos
    sdk: dev
  - analyze:
    sdk: dev
- unit_test:
  - test:
    sdk: [dev, pubspec]
  - test: --run-skipped -t presubmit-only
    sdk: [dev]
