# https://github.com/google/mono_repo.dart
sdk:
- pubspec
- dev

stages:
- analyze_format:
  - group:
    - format
    - analyze: --fatal-infos .
    sdk: dev
  - group:
    - analyze: .
    sdk: 2.17.0
- unit_test:
  - test: -x presubmit-only
  - test: --run-skipped -t presubmit-only
