# https://github.com/google/mono_repo.dart
sdk:
- pubspec
- dev

stages:
- analyze_format:
  - group:
    - format
    - analyze: --fatal-infos
    sdk: dev
  - analyze:
    sdk: pubspec
- unit_test:
  - test: -x presubmit-only
  - test: --run-skipped -t presubmit-only
    sdk: dev
