# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    sources:
      include:
        - $package$
        - pubspec.yaml
        - lib/**
        - templates/**
        - tool/**
    builders:
      dartfn:
        generate_for:
          - lib/src/generators/*.dart
        enabled: true

builders:
  dartfn:
    import: "tool/builder/builder.dart"
    builder_factories: ["builder"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source
