# https://github.com/google/mono_repo.dart

stages:
- analyze_format:
  - group:
      - format
      - analyze: --fatal-infos
    sdk: stable # main - debug this!
# Need to figure why main/master doesn't work!
#  - group:
#      - analyze
#    sdk: stable
#
