# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://pub.dev/packages/lints.
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
#   exclude:
#     - path/to/excluded/files/**

# This is here to fix CI analysis. Will be removed at generation.
# Search source code for details
linter:
  rules:
    lowercase_with_underscores: 'no'
