# https://github.com/google/mono_repo.dart
dart:
- dev
- 2.12.0

stages:
- analyze_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .
    dart: dev
  - group:
    - dartanalyzer: .
    dart: 2.12.0
- unit_test:
  - group:
    - test:
  - group:
    - test: --run-skipped -t presubmit-only
    dart: dev
