# https://github.com/google/mono_repo.dart
sdk:
- dev
- pubspec

stages:
- analyze_format:
  - group:
    - format
    - analyze: --fatal-infos .
    dart: dev
  - group:
    - analyze: .
    dart: pubspec
- unit_test:
  - group:
    - test:
  - group:
    - test: --run-skipped -t presubmit-only
    dart: dev
