# https://github.com/google/mono_repo.dart
dart:
- dev
- 2.14.0

stages:
- analyze_format:
  - group:
    - format
    - analyze: --fatal-infos .
    dart: dev
  - group:
    - analyze: .
    dart: 2.14.0
- unit_test:
  - group:
    - test:
  - group:
    - test: --run-skipped -t presubmit-only
    dart: dev
