name: gcp
publish_to: none
description: >-
  Utilities for running Dart code correctly on the Google Cloud Platform.
# After changing the version, run `pub run build_runner build`.
version: 0.1.0-dev
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart/tree/main/gcp

environment:
  sdk: ^2.18.0

dependencies:
  http: ^0.13.5
  shelf: ^1.4.0

dev_dependencies:
  googleapis: ^9.2.0
  googleapis_auth: ^1.3.1
  lints: ^2.0.0
  test: ^1.22.0
  test_process: ^2.0.3
