name: gcp
description: >-
  Utilities for running Dart code correctly on the Google Cloud Platform.
version: 0.1.1-dev
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart/tree/main/gcp

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  http: ^0.13.5
  io: ^1.0.3
  shelf: ^1.4.0
  stack_trace: ^1.11.0

dev_dependencies:
  googleapis: ^10.1.0
  googleapis_auth: ^1.3.1
  lints: ^2.0.0
  test: ^1.22.0
  test_process: ^2.0.3
