name: gcp
description: >-
  Utilities for running Dart code correctly on the Google Cloud Platform.
version: 0.1.2-wip
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart/tree/main/gcp

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.17.0
  http: '>=0.13.5 <2.0.0'
  io: ^1.0.3
  shelf: ^1.4.0
  stack_trace: ^1.11.0

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.3.1
  test: ^1.22.0
  test_process: ^2.0.3
