name: gcp
description: >-
  Deprecated. Use pkg:google_cloud instead
version: 0.2.0
repository: https://github.com/GoogleCloudPlatform/functions-framework-dart/tree/main/gcp

environment:
  sdk: ^3.0.0

dependencies:
  # Maintain a narrow constraint since APIs from this package are exported.
  google_cloud: '>=0.2.0 <0.2.1'

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.3.1
  shelf: ^1.4.1
  test: ^1.22.0
  test_process: ^2.0.3

dependency_overrides:
  google_cloud:
    path: ../google_cloud
