name: markdown_linter
on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: xt0rted/markdownlint-problem-matcher@v1
    - run: markdownlint **/*.md --ignore node_modules
