name: markdown_linter
on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install --global markdownlint-cli2
    - name: Run lint check
      run: markdownlint-cli2 **/*.md
  markdown_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --global markdownlint-cli2
    - name: Run lint check
      run: markdownlint-cli2-fix **/*.md
