name: markdown_linter
on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
        config_file: .github/workflows/mardown_linter_rules.yaml
