# A CI configuration to auto-publish pub packages.

name: Publish

on:
  pull_request:
    branches: [ main ]
  push:
    tags: [ '[A-z]+-v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:
  publish:
    if: ${{ github.repository_owner == 'GoogleCloudPlatform' }}
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
